#!/bin/sh

mkdir -p /mnt/mmc
mkdir -p /mnt/mmc0

while true; do
	if test -e /dev/mmcblk0p1; then
	break
	else
	echo "not mount"
	sleep 1
	continue
	fi
done
mount /dev/mmcblk0p1 /mnt/mmc0
wait
insmod /root/vr.ko
insmod /root/nx_vpu.ko
 
#root/svt_main &

